CREATE TABLE QUESTION(
    QUESTION_TYPE VARCHAR(30),
    QUESTION_DESCRIPTION CLOB,
    DIFFICULTY_LEVEL VARCHAR(10),
    CHOICE_1 CLOB,
    CHOICE_2 CLOB,
    CHOICE_3 CLOB,
    CHOICE_4 CLOB,
    ANSWER_1 BOOLEAN,
    ANSWER_2 BOOLEAN,
    ANSWER_3 BOOLEAN,
    ANSWER_4 BOOLEAN,
    T_OR_F_ANSWER BOOLEAN,
    FIB_ANSWER VARCHAR(300)
);